### ISSUE TITLE
Allow downloading all contents on this website as soon as possible.

### ISSUE THREAD

**Issue by hadi99905** [femto-apps/web-file-uploader#50] opened 2021-02-26 11:55 UTC
I'm not able to download files uploaded on this website make download available as soon as possible.Please

**Comment by dimaguy** [comment] 2021-02-26 13:32
Files are supposed to be available as soon as they are uploaded. Are you sure the upload completed successfully?

**Comment by hadi99905** [comment] 2021-02-26 13:38
Yes it is uploaded i will give link of the file
https://femto.pw/umpc
I am not able to download the file can you pls help me

**Comment by dimaguy** [comment] 2021-02-26 13:40
That link corresponds to a static html file, which is rendered by femto. Youll need to "save link as" or curl/wget it

**Comment by hadi99905** [comment] 2021-02-26 13:41
Could you please help me download it.It would be a great thing from you.

**Comment by dimaguy** [comment] 2021-02-26 13:42
I already gave you all instructions you need, I dont know what else to tell you, just right click the link and click save link as

**Comment by hadi99905** [comment] 2021-02-26 13:45
I am using mobile there is no option "save link as" that file is so
important to me

**Comment by hadi99905** [comment] 2021-02-26 13:47
Can you provide a link to directly download that file.

**Comment by popey456963** [comment] 2021-02-28 12:47
I'm closing this as it's not a bug with `web-file-uploader`.

**Closed by popey456963** 2021-02-28 12:47 UTC

**Comment by hadi99905** [comment] 2021-02-28 12:49
Can you give me the link please

**Comment by hadi99905** [comment] 2021-02-28 12:52
Can you please give me his email address? Just once.Please sir i request🙏

**Comment by dimaguy** [comment] 2021-02-28 12:54
You ALREADY have both the link and instructions to get the html file

**Comment by hadi99905** [comment] 2021-02-28 12:55
I want the pdf not the html file

**Comment by dimaguy** [comment] 2021-02-28 12:57
There is no pdf in that file. I am sorry but on that link there is only an html static page

**Comment by hadi99905** [comment] 2021-02-28 12:59
He uploaded 2.00gb file i am looking forward to download that.

**Comment by dimaguy** [comment] 2021-02-28 12:59
He uploaded the wrong thing. I am sorry

**Comment by hadi99905** [comment] 2021-02-28 13:01
You are saying that coz you don't know what to do lol😂

**Comment by dimaguy** [comment] 2021-02-28 13:04
I know fairly well what to do: tell you to ring your friend so he uploads the right thing.

HE DID NOT UPLOAD THE PDF FILE AS YOU CAN SEE ON THIS LINK

https://femto.pw/info/umpc

**Comment by hadi99905** [comment] 2021-02-28 13:07
Please help me could you please give me his email address please

**Comment by dimaguy** [comment] 2021-02-28 13:10
That is against GDPR, so not even the owner can provide such thing.

**Comment by hadi99905** [comment] 2021-02-28 13:11
So what should I do? I want that file how can i contact him i saw only one
file on internet.

**Comment by dimaguy** [comment] 2021-02-28 13:27
You are out of luck
